# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import network.cas_proto_pb2 as cas__proto__pb2


class UploaderStub(object):
  """The uploading service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Upload = channel.unary_unary(
        '/cas_proto.Uploader/Upload',
        request_serializer=cas__proto__pb2.UploadRequest.SerializeToString,
        response_deserializer=cas__proto__pb2.UploadReply.FromString,
        )


class UploaderServicer(object):
  """The uploading service definition.
  """

  def Upload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UploaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Upload': grpc.unary_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=cas__proto__pb2.UploadRequest.FromString,
          response_serializer=cas__proto__pb2.UploadReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cas_proto.Uploader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
