# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cas_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cas_proto.proto',
  package='cas_proto',
  syntax='proto3',
  serialized_options=_b('\n\032io.grpc.examples.cas_protoB\010CASProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0f\x63\x61s_proto.proto\x12\tcas_proto\"+\n\rUploadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1e\n\x0bUploadReply\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x08Uploader\x12<\n\x06Upload\x12\x18.cas_proto.UploadRequest\x1a\x16.cas_proto.UploadReply\"\x00\x42.\n\x1aio.grpc.examples.cas_protoB\x08\x43\x41SProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='cas_proto.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cas_proto.UploadRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cas_proto.UploadRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)


_UPLOADREPLY = _descriptor.Descriptor(
  name='UploadReply',
  full_name='cas_proto.UploadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='cas_proto.UploadReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['UploadReply'] = _UPLOADREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADREQUEST,
  __module__ = 'cas_proto_pb2'
  # @@protoc_insertion_point(class_scope:cas_proto.UploadRequest)
  ))
_sym_db.RegisterMessage(UploadRequest)

UploadReply = _reflection.GeneratedProtocolMessageType('UploadReply', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADREPLY,
  __module__ = 'cas_proto_pb2'
  # @@protoc_insertion_point(class_scope:cas_proto.UploadReply)
  ))
_sym_db.RegisterMessage(UploadReply)


DESCRIPTOR._options = None

_UPLOADER = _descriptor.ServiceDescriptor(
  name='Uploader',
  full_name='cas_proto.Uploader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='cas_proto.Uploader.Upload',
    index=0,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_UPLOADREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOADER)

DESCRIPTOR.services_by_name['Uploader'] = _UPLOADER

# @@protoc_insertion_point(module_scope)
